export const FETCH_ACCOUNTS_SUCCESS = 'FETCH_ACCOUNTS_SUCCESS';
export const FETCH_ACCOUNTS_FAILURE = 'FETCH_ACCOUNTS_FAILURE,';
export const FETCH_ACCOUNTS_REQUEST = 'FETCH_ACCOUNTS_REQUEST';

export const DETAILS_ACCOUNT_SUCCESS = 'DETAILS_ACCOUNT_SUCCESS';
export const DETAILS_ACCOUNT_FAILURE = 'DETAILS_ACCOUNT_FAILURE,';
export const DETAILS_ACCOUNT_REQUEST = 'DETAILS_ACCOUNT_REQUEST';
