//get all
export const ALL_MESSAGES_SUCCESS = 'ALL_MESSAGES_SUCCESS';
export const ALL_MESSAGES_FAILURE = 'ALL_MESSAGES_FAILURE';
export const ALL_MESSAGES_REQUEST = 'ALL_MESSAGES_REQUEST';

//create
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';
export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST';
